### ISSUE TITLE
Docker pg01 start issue

### ISSUE THREAD

**Issue by OliverCole** [kanishka-linux/reminiscence#1]
When I do `docker-compose up --build`, I get this:

```
Starting pg01 ... done
Starting dg01 ... done
Creating ng01 ... done
Attaching to pg01, dg01, ng01
pg01     | 2018-09-09 15:57:20.932 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
pg01     | 2018-09-09 15:57:20.932 UTC [1] HINT:  The server must be started by the user that owns the data directory.
pg01 exited with code 1
dg01     | db: forward host lookup failed: Unknown host
dg01     | db: forward host lookup failed: Unknown host
```

**Comment by OliverCole** [comment]
Looks like this is just https://github.com/docker/for-win/issues/445. Could perhaps add Windows specific instructions.

**Comment by kanishka-linux** [comment]
I have not tested docker method on windows. Thanks for pointing out reference. Is the solution mentioned in the reference working for you? If it is working, then I'll add windows specific instructions.

**Comment by OliverCole** [comment]
Yes - [this specific comment](https://github.com/docker/for-win/issues/445#issuecomment-405185621) worked for me.

**Comment by kanishka-linux** [comment]
Thanks for testing it on Windows. It was great help!
