### ISSUE TITLE
No matching distribution found for aiohttp==3.3.2

### ISSUE THREAD

**Issue by danmed** [kanishka-linux/reminiscence#10]
running Ubuntu 16.04

Any ideas? the versions listed only go up to 3.0.0b0

**Comment by kanishka-linux** [comment]
In ubuntu 16.04, it is best to use docker based method. aiohttp 3.3.2 won't work with python 3.5.
However if you still want to use normal method, then simply remove aiohttp and related dependencies from requirements.txt and in settings.py set VINANTI_BACKEND = 'urllib'. Reminiscence can work without aiohttp but performance suffers little bit which may or may not be noticeable to user.
