### ISSUE TITLE
logo design contribution

### ISSUE THREAD

**Issue by reallinfo** [kanishka-linux/reminiscence#15]
Hi @kanishka-linux 

I am designing logos to contribute to open source software. To make projects more recognizable... I can design a few logo samples for you if you want. I'll wait for feedback. Thanks!

**Comment by kanishka-linux** [comment]
> To make projects more recognizable... I can design a few logo samples

That's a good idea. You're welcome to do so. I'm not good at designing, so any help in this respect will be great!

**Comment by reallinfo** [comment]
Hi again, i designed a logo. How do these look? Please tell me if there's anything you want to change.

![remi](https://user-images.githubusercontent.com/36298335/47306700-db8f1c00-d635-11e8-8be2-d09131cddb2c.jpg)
![rem2](https://user-images.githubusercontent.com/36298335/47306706-dfbb3980-d635-11e8-8177-ef170cad6bce.jpg)

**Comment by reallinfo** [comment]
Hi again, thank you.  I'll make changes soon.

**Comment by kanishka-linux** [comment]
No need to hurry. Take your time.

In case, you want to test the logo on your own, follow following steps:

* install reminiscence using normal method as per instructions given in the documentation

* Create **logo** directory inside **static** folder, and put sample logos there

* now open templates/base.html file and find 'navbar-brand' class. Inside this tag, create img tag which will look like

        <img src="{% static 'logo/sample.svg' %}">

* Now make changes in the logo and just refresh page to see the effect

If you've any problem in following above points, then just make a pull request against [testing](https://github.com/kanishka-linux/reminiscence/tree/testing) branch. I'll test the logo.

**Comment by reallinfo** [comment]
I've added a few variations on the black navbar. How is these?  Is that what you mean? When you make a decision, I will send a PR via testing branch. Because, Unfortunately
 i can't use github very well.

![r4](https://user-images.githubusercontent.com/36298335/47436654-8e36ba00-d7af-11e8-8d15-43092cdf6e8d.jpg)

**Comment by kanishka-linux** [comment]
All the variations are looking good. You can send all of them, including other variants which you posted before. I will try them out.

**Comment by reallinfo** [comment]
I would be very pleased if you share the result with me at the end of the job. I wonder how it will look :) 

now I will prepare all the files and send a pr.

**Comment by kanishka-linux** [comment]
sure!

**Comment by reallinfo** [comment]
I sent a pr. I've added all variations. (png and svg files.)

**Comment by reallinfo** [comment]
I made all the changes you want and I sent a pr of the master branch. I'm closing this issue with your permission. You can still write any problems. Thanks. Goodoworks...

https://github.com/kanishka-linux/reminiscence/pull/17
