### ISSUE TITLE
Subfolder Support

### ISSUE THREAD

**Issue by JPT62089** [kanishka-linux/reminiscence#21]
This type of self-hosted software is exactly what I am looking for, however, there is one thing that makes me not want to use it... I like folders... Lots of folders... Organization with only a top level folder would be a nightmare to manage and find things... Can we have the ability to create unlimited subfolders?

**Comment by kanishka-linux** [comment]
I was also thinking about it for some time. But can't say for sure when will it be implemented. I'll add this feature in future roadmap.

**Comment by NoverNobida** [comment]
@kanishka-linux  How to create sub-directory? I can't find anywhere.

**Comment by kanishka-linux** [comment]
If you've installed from latest master branch, then go to any folder, and click on the `Menu` - which is available at the right corner title header. You'll find `Create Sub-Dir` option - which will create subdirectory within given directory.

**Comment by NoverNobida** [comment]
@kanishka-linux I found it, thanks!
