### ISSUE TITLE
reminisence on nginx can't show reminisence page?

### ISSUE THREAD

**Issue by yamatakau08** [kanishka-linux/reminiscence#23]
My environment is Linux Mint.

I'm trying to use "reminiscence" through Nginx by refereing following page.
[https://github.com/kanishka-linux/reminiscence/blob/master/README.md#gunicorn-plus-nginx-setup](url)

Both 
`(venv) yama@jpx20120007:~/reminiscence/venv/reminiscence$ python manage.py runserver 127.0.0.1:8000`
and
`(venv) yama@jpx20120007:~/reminiscence/venv/reminiscence$ gunicorn --max-requests 100 --worker-class gthread --workers 2 --thread 5 --timeout 300 --bind 0.0.0:8000 reminiscence.wsgi`
work fine.

Since I can see "Welcome to nginx" http://localhost/, nginx woks fine.

But 
http://localhost/static shows "404 Not found"
http://127.0.0.1:8000 shows "ERR_CONNECTION_REFUSED"

Could you advise me what is wrong is?

my nginx reminiscence.conf is here.
```
(venv) yama@jpx20120007:~/reminiscence/venv/reminiscence$ cat /etc/nginx/conf.d/reminiscence.conf 
#worker_processes  2;
  
#events {
\#    worker_connections  1024;
#}

#http {
\#   include       mime.types;
\#   default_type  application/octet-stream;

\#   sendfile        on;
\#   sendfile_max_chunk 512k;
\#   keepalive_timeout  65;
\#   proxy_read_timeout 300s;

    server {
	listen       80;
	server_name  localhost;
	client_max_body_size 1024m;
      
	location /static/ {
		root /home/yama/reminiscence/venv/reminiscence; # root of project directory
		aio threads;
        }
	location = /favicon.ico { access_log off; log_not_found off; }
	location / {
        	 proxy_pass http://127.0.0.1:8000;
		 proxy_set_header Host $host;
		 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		 root /home/yama/reminiscence/venv/reminiscence; #root of project directory
	}

 	error_page   500 502 503 504  /50x.html;
 	location = /50x.html {
 	root   /usr/share/nginx/html;
 	}
    }
\#}
```
nginx confile syntax is ok.

```yama@jpx20120007:/etc/nginx/conf.d$ sudo nginx -t
[sudo] yama のパスワード:
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Comment by kanishka-linux** [comment]
Try to find out local ip address of machine using command

        ifconfig

if it is something like 192.168.1.4, then try opening 

        http://192.168.1.4/

do not attach port number to it.

**Comment by yamatakau08** [comment]
I should have executed reminiscence through nginx. But I didn't do that.
After executing reminiscence with gunicron, it works fine.
Sorry for bothering you.
