### ISSUE TITLE
Is there a REST API?

### ISSUE THREAD

**Issue by virtadpt** [kanishka-linux/reminiscence#27]
Is there a REST API for Reminiscence?  I just did a couple of quick searches and didn't find any mention of one.

**Comment by kanishka-linux** [comment]
Current API is not exactly RESTful, since it uses cookies and csrf tokens for managing session.
Providing some token/key based REST API is on to-do list. However, I'm not sure whether to provide RESTful or GraphQL API, I'll think about it.

**Comment by virtadpt** [comment]
A polite +1 for a RESTful API, please.

**Comment by kanishka-linux** [comment]
I've exposed few functionalities of `reminiscence` using `django rest framework`. 
The new rest api is mostly enough for getting authentication token and adding urls to a directory. (Good enough for developing browser addons). 

Currently, one can get idea about api by looking at these [tests](https://github.com/kanishka-linux/reminiscence/blob/master/tests/tests_drf.py). I'll write proper documentation after some time.
