### ISSUE TITLE
How can save webpages that requiere an account?

### ISSUE THREAD

**Issue by vinanrra** [kanishka-linux/reminiscence#32]
I want to save webpages that requiere an account, i already have one but i dont know how i will be able to login.

I use docker container, but if neccessary i can use a raspberry without docker.

**Comment by kanishka-linux** [comment]
Currently there is no straightforward way to do it. Maybe if you can export browser's session/cookies to the headless browser at the server side, then you might be able to do it. But I haven't tried it yet, so not sure whether it will work or not.
