### ISSUE TITLE
[HELP] When trying to login, reminiscence report Forbidden error (403)

### ISSUE THREAD

**Issue by mzch** [kanishka-linux/reminiscence#33]
When I tried to login, reminiscence report Forbidden error (403).
```
Forbidden (403)
CSRF verification failed. Request aborted.
You are seeing this message because this HTTPS site requires a 'Referer header' to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.
If you have configured your browser to disable 'Referer' headers, please re-enable them, at least for this site, or for HTTPS connections, or for 'same-origin' requests.
If you are using the <meta name="referrer" content="no-referrer"> tag or including the 'Referrer-Policy: no-referrer' header, please remove them. The CSRF protection requires the 'Referer' header to do strict referer checking. If you're concerned about privacy, use alternatives like <a rel="noreferrer" ...> for links to third-party sites.
```
How can I fix this issue?

Python: 3.6.10
Browser: Google Chome 79.0.3945.130, Safari 13.0.4 (15608.4.9.1.3), Firefox 72.0

**Comment by kanishka-linux** [comment]
Can you mention OS or which distro you are using?

**Comment by mzch** [comment]
My reminiscence runs on Linux, Debian 10 (Buster).

**Comment by kanishka-linux** [comment]
can you remove this line: https://github.com/kanishka-linux/reminiscence/blob/master/templates/base.html#L8 from the source and run the server again?

**Comment by mzch** [comment]
Great! I can login. Thanks!

**Comment by mzch** [comment]
Could you tell me that this happen on Debian 10?

**Comment by kanishka-linux** [comment]
Not sure why this happens on debian 10. Maybe the issue is related to the latest version of django. Anyway good to see that above hack is working for you :)

**Comment by mzch** [comment]
Thanks! :)
