### ISSUE TITLE
Docker won't install i/o timeout

### ISSUE THREAD

**Issue by RyanLiRui** [kanishka-linux/reminiscence#34]
What should I do here? I can't pull the required data for the docker install. See screenshot below.

![cantpull](https://user-images.githubusercontent.com/977609/72766517-3ba2b280-3c2b-11ea-8a6e-37d9387b281c.jpg)

**Comment by kanishka-linux** [comment]
Maybe it is dns related issue. Try pinging the host where you are getting timeout to see whether the host is reachable or not.

**Comment by RyanLiRui** [comment]
Well like you can see in the screenshot I did do that, and I can reach the host via pinging it.
