### ISSUE TITLE
docker-compose up --build : Error: postgress container doesn't start up but throws error

### ISSUE THREAD

**Issue by s3h10r** [kanishka-linux/reminiscence#39]
Hi,

couldn't get the project running via docker because: 

When doing `sudo docker-compose up --build` the db container doesn't start up but throws error:

```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD for the superuser. Use
       "-e POSTGRES_PASSWORD=password" to set it in "docker run".

       You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
       without a password. This is *not* recommended. See PostgreSQL
       documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

this is related to [this breaking change in image postgres](https://github.com/docker-library/postgres/commit/42ce7437ee68150ee29f5272428aa4fc657dc6dc) and discussed [here](https://github.com/docker-library/postgres/issues/681)

setting the env vars in `docker-compose.yml` fixes this.
i'll send you a pull request for this (hope you don't mind).

greetings, Sven

**Comment by kanishka-linux** [comment]
Thanks for reporting the issue.
> 'll send you a pull request for this (hope you don't mind). 

Sure. Will take a look at it this weekends.
