### ISSUE TITLE
No Access From Other Machines On LAN

### ISSUE THREAD

**Issue by bonfiredog** [kanishka-linux/reminiscence#43]
Cannot seem to access from other machines on my LAN - connection times out.

Attempted with:
- hostname;
- Local IP.

Have created ufw exceptions for Port 8000, but no avail.

**Comment by kanishka-linux** [comment]
what method are you using for installation? Regular or docker based?

**Comment by bonfiredog** [comment]
Apologies this was my own stupid mistake, starting the server on localhost only.
