### ISSUE TITLE
Docker image does not found static content

### ISSUE THREAD

**Issue by daitangio** [kanishka-linux/reminiscence#46]
Ref: commit 829963549c6170034f3d01619ceeb194e376084b 
Running docker compose as in README, we are unable to get the static part.
A lot of error on web_1 like:

>web_1    | /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
web_1    |   """)
>web_1    | WARNING:django.request:Not Found: /static/css/bootstrap.min.css
...
>WARNING:django.request:Not Found: /static/js/main.js

How can we fix it?

**Comment by kanishka-linux** [comment]
maybe similar [issue](https://github.com/kanishka-linux/reminiscence/issues/8)

**Comment by daitangio** [comment]
Yeah duplicated of issue #8
