### ISSUE TITLE
Firefox-Addon ported to Chromium/Chrome

### ISSUE THREAD

**Issue by s3h10r** [kanishka-linux/reminiscence#47]
Hi, btw. ported Alec's Firefox-Addon to Chromium/Chrome because i couldn't find one. Works fine for me, so maybe it can be usefull for others too:

https://github.com/s3h10r/AddToReminiscence-Chromium-Extension

Greetings,
Sven

**Comment by kanishka-linux** [comment]
Hey Sven,

Thanks a lot! It will be surely useful for chrome/chromium users.

**Comment by s3h10r** [comment]
YWA, it's not a bug / works at least fine for me - closing this issue. just wanted to let you and chromium users know and wasn't sure what's the right channel. :) Greetings & thx for Reminiscence, Sven

**Comment by kanishka-linux** [comment]
> just wanted to let you and chromium users know and wasn't sure what's the right channel.

you are always welcome! :)

I'll update the wiki with the link to chromium extension.
