### ISSUE TITLE
Merging Folders and multiple select

### ISSUE THREAD

**Issue by DooDip** [kanishka-linux/reminiscence#5]
Thank you for this project, it is AWESOME!!

I have one issue. I have imported several Bookmark backup and for whatever reason it has imported the same folder as 
"Foldername"
"Foldername 1"

An example is I have an Arduino bookmarks folder on 2 computers. After importing it shows up as
"Arduino"
"Arduino 1"

Is there an easy way to merge both folders? Are there any plans to have a check-box to select multiple bookmarks and move them to another folder or tag them? I've been pretty happy with Buku server but it doesn't implement the archiving and auto-tagging. However, it does allow you to easily merge/move bookmarks around.

Thanks for this project!!

**Comment by kanishka-linux** [comment]
> Is there an easy way to merge both folders?

Merging two folders with different content is pretty easy. Just rename two folder and set a common name. But it won't remove duplicates. I think, giving special merge option would be a lot better and It is also easier to implement. Hopefully, I'll try to implement it this weekend.

>Are there any plans to have a check-box to select multiple bookmarks and move them to another folder..?

Backend code required for this feature has already been there, only frontend side of code needs to be implemented. If it is easier to implement, I'll look into it in coming days.

>Thanks for this project!!

You're most welcome!

**Comment by kanishka-linux** [comment]
Following features have been landed in devel branch

1. Merging folders
2. Select check-boxes 
3. multiple select for moving/tagging/archiving

A drop-down menu has been added at the Action header with multiple options (available inside directories). 

Users can test new features, but do not test it on existing database and archive collection.
