### ISSUE TITLE
static files result in 404 when using docker installation

### ISSUE THREAD

**Issue by beac0n** [kanishka-linux/reminiscence#8]
when using the docker installation, all static assets (js and css files) result in a 404,
which makes the site look like a basic html site

**Comment by kanishka-linux** [comment]
In docker installation, you don't have to use to port number in url. I think most probably, you are trying to access server by using url format similar to "http://192.168.1.5:8000/". Just remove port number and simply use 'http://192.168.1.5/' to access server. If you want the server to listen at particular port number then you'll have to edit docker-compose.yml and adjust port settings in nginx section accordingly.
